<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="<?= $basePath ?>">PrePressTricks</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Utilities</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Utilities&p=Boxes">Boxes</a>
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Utilities&p=Pages">Pages</a>
                </div>
            </li>
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Ticketing</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Ticketing&p=StringToTicket">StringToTicket</a>
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Ticketing&p=01_XpifTicketMakerSimple">01_XpifTicketMakerSimple</a>
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Ticketing&p=02_XpifTicketMakerComplex">02_XpifTicketMakerComplex</a>
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Ticketing&p=03_XpifTicketMakerInsertSheet">03_XpifTicketMakerInsertSheet</a>
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Ticketing&p=04_ForTheTermOfHisNaturalLifePdf">04_ForTheTermOfHisNaturalLifePdf</a>
                </div>
            </li>
        </ul>


        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Graphics</a>
                <div class="dropdown-menu" aria-labelledby="dropdown03">
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Graphics&p=Ghostscript">Ghostscript</a>
                    <a class="dropdown-item" href="<?= $basePath ?>?f=Graphics&p=ImageMagick">ImageMagick</a>
                </div>
            </li>
        </ul>

    </div>
</nav>